### PR TITLE
Add duplication menu action on cmd+d

### PR DESCRIPTION
**Pull request by AgapovOne**
Added keyboard shortcut for duplication

`cmd + d` to Duplicate.

That creates a copy of selected control moved by `{40,40}` offset

Used a new action listeners array that has access to presenter. Nothing leaks, I checked.

<details><summary>Video</summary>
<p>

https://github.com/VODGroup/VoiceOverDesigner/assets/4246455/19096947-279c-42b7-bc82-cd0afe6b882e

Screenshot 2023-09-28 at 00 32 28

</p>
</details>

### CODE REVIEW

**Comment by akaDuality** [comment]
@AgapovOne thank you, duplication will be very usefull.

Not sure that it is a correct implementation for macOS. 

I should have "duplicate" action in Edit menu. As a result I can remap any action from menu to another button and this action should check this remapping in code. Can you try another approach?

Exampes:
- ["Add Image" action from canvas submenu ](https://github.com/VODGroup/VoiceOverDesigner/blob/2be21860b119854cfd16bf8d316b46f021a2fbd2/VoiceOver%20Designer/Features/Sources/CanvasAppKit/CanvasViewController.swift#L103)
- [Actions in document menu](https://github.com/VODGroup/VoiceOverDesigner/blob/2be21860b119854cfd16bf8d316b46f021a2fbd2/VoiceOver%20Designer/Features/Sources/Recent/RecentViewController/Domain/UserDocuments/UserDocumentsPresenter.swift#L56)

**Comment by AgapovOne** [comment]
Menu items are better, for sure :)
Thanks

<details><summary>Details</summary>
<p>

Screenshot 2023-09-28 at 09 05 43

</p>
</details> 

It would be better to somehow separate menu actions from view controller and move them (like you moved drag actions). But that's a topic for later when we'll see how many actions there are.

**Comment by AgapovOne** [comment]
<details><summary>Details</summary>
<p>

Screenshot 2023-09-28 at 10 36 39

</p>
</details>

Also I found document where it is possible to use selectors and modify edit actions copy/paste.

Probably it's better to add Duplicate there and support copy/paste?

If I would do that I need to:
- access selectedControl from VODesignDocument. Might add it to VODesignDocumentProtocol
- define copy/paste data format. Codable json that can be pasted into any text editor/messenger?

**Review by akaDuality — APPROVED** [review]

**Comment by akaDuality** [comment]
Default copy/paste is cool, never thought about it. Can you create the new issue and attach some links?

- We can move selectedControl to VODesignDocument
- Json of single element if fine

**Pull request merged**
