### PR TITLE
Add labels over rectangles

### PR DESCRIPTION
**Pull request by drucelweisse**
# Description
This pr contains changes about label near drawn rectangle

## Changes

- Added CATextLayer to A11yControl that shows A11yDescription label
- Added setting layer string value in SettingsPresenter.updateLabel(to newValue: String)
# Related Issue
* #9

# Screenshots

https://user-images.githubusercontent.com/36012972/177398428-93974891-a8fe-49f6-9e35-e48198803bb6.mp4

### CODE REVIEW

**Comment by drucelweisse** [comment]
## Need to do: 

- [ ] Setting that will make CATextLayer optional to show.
- [ ] tests for invalidate layer string value

Should it be setting per file or global setting for application?

**Comment by akaDuality** [comment]
Cool!

> Should it be setting per file or global setting for application?
We can add toolbar with the setting to enable/disable it on the fly. Probably, the toolbar brokes coordinates calculation because  it calculates from window coordinates and toolbar add extra height

**Comment by drucelweisse** [comment]
I've added toolbar to EditorViewController, and showingLabels settings based on button state. I'm not sure about it, is it correct approach to manipulate that setting?

https://user-images.githubusercontent.com/36012972/177855213-7294409b-43bc-4769-9708-b904e7cad591.mp4

**Comment by akaDuality** [comment]
Fine!

**Comment by drucelweisse** [comment]
Yeah, merge it

**Comment by akaDuality** [comment]
I've merged, thank you!

**Pull request merged**
