### PR TITLE
Designer App transition to SPM

### PR DESCRIPTION
**Pull request by drucelweisse**
# Description
This pr contains changes about transition Designer App to Swift Package Manager structure. It's aimed to reduce signing problems to other contributors

## Changes

- Added Swift Package, package manifest
- Moved following targets: Projects, Editor, Settings, CommonUI
- Moved following test targets: EditorTests, SettingsTests, ProjectsTests
- Fixed Storyboards processing with SPM

## Removed

- Removed old Xcode framework targets

### CODE REVIEW

**Comment by akaDuality** [comment]
It's strange, but my NSDocumentController loose all recent files. Do you have same problem?

**Comment by drucelweisse** [comment]
Yeah I had it too, it's because of none development team and "Sign to run locally" certificate. On start it'll show this error:

`Failed to get state for list identifier com.apple.LSSharedFileList.ApplicationRecentDocuments Error: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (Access to list denied) UserInfo={NSDebugDescription=Access to list denied}`

 I have set my dev team and "Development" certificate to show files, but not committed it

**Comment by akaDuality** [comment]
Understood, thank you! Will check PR thin evening

**Review by akaDuality — APPROVED** [review]

**Comment by akaDuality** [comment]
Also I have updated [How to launch page](https://github.com/VODGroup/VoiceOverDesigner/wiki)

**Pull request merged**
