### PR TITLE
Add standard share menu to toolbar

### LINKED ISSUE #206: Add standard share menu to toolbar
Every time iCloud is getting stack for me and I share via Air Drop. To do this I should go to finder, find file, etc.

Would like to share straight from the app.

### PR DESCRIPTION
**Pull request by drucelweisse**
Closes #206 

Added NSSharingServicePickerToolbarItem and conformed VODesignDocument as provider delegate to share an url.

Tried with Notes, Airdrop, Messages. Also tried to share via Telegram but it doesn't accept it :(

### CODE REVIEW

**Comment by akaDuality** [comment]
For me button isn't visible. The same and for leading panel's button.

**Comment by drucelweisse** [comment]
Oh, that's quite odd...

**Comment by akaDuality** [comment]
Just fond in Console.app: `NSToolbarDelegate of class VoiceOver_Designer.ProjectController returned an item with identifier TrailingSidebar when asked for an item with identifier LeadingSidebar`

**Comment by drucelweisse** [comment]
At least we have an error message to start with. But it seems odd as we switch value correctly)
https://github.com/VODGroup/VoiceOverDesigner/pull/212/files#diff-213604d969e71d8a897f33163aa2d42923449c300ba1c2fa0006848e5bd6d1f2R17-R18

**Comment by drucelweisse** [comment]
@akaDuality found culprits)

**Review by akaDuality — APPROVED** [review]

**Comment by akaDuality** [comment]
Works at my Mac now, thank you! 

Have update branch to pass tests

**Pull request merged**
